### ISSUE TITLE
[ Some Page ] Title Remains Cryptoearth for IBINEX Blog

### ISSUE THREAD

**Issue by ghuerte** [IbinexPH/ibinex-blog#1]
http://10.128.146.135/ibinex-blog/cryptocurrency-gets-spicy-with-habanero-backed-token/

![image](https://user-images.githubusercontent.com/37136794/39460721-64115110-4d38-11e8-9b6b-0035a2fa1197.png)

**Comment by kevinpayas** [comment]
already fixed
