### ISSUE TITLE
[ Jobs ] Title Remains Cryptoearth for IBINEX Blog

### ISSUE THREAD

**Issue by ghuerte** [IbinexPH/ibinex-blog#2]
![image](https://user-images.githubusercontent.com/37136794/39460763-a6b3a996-4d38-11e8-87e7-a7dc70973659.png)

**Comment by ghuerte** [comment]
http://blogsite-ibinex.a3c1.starter-us-west-1.openshiftapps.com/jobs/

**Comment by kevinpayas** [comment]
cryptoearthofficial@gmail.com change to ibinexofficial@ibinex.tech
