### ISSUE TITLE
[ About Us ] Title Remains Cryptoearth for IBINEX Blog

### ISSUE THREAD

**Issue by ghuerte** [IbinexPH/ibinex-blog#3]
![image](https://user-images.githubusercontent.com/37136794/39460881-8e040d9a-4d39-11e8-8c00-edf172d50cee.png)

**Comment by ghuerte** [comment]
http://blogsite-ibinex.a3c1.starter-us-west-1.openshiftapps.com/jobs/

**Comment by kevinpayas** [comment]
cryptoearth.cc change to ibinex.tech..

**Comment by ghuerte** [comment]
![image](https://user-images.githubusercontent.com/37136794/39463866-12851308-4d4d-11e8-8a60-cf21169e6c82.png)
